### ISSUE TITLE
Initial organizational work

### ISSUE THREAD

**Issue by rgrempel** [elm-community/Manifesto#1]
Greetings, @elm-community/manifesto 

So, thanks for accepting the invitation to join this little enterprise -- I hope this ends up being a useful way of doing some collaborative things.

In order to move organizational discussion and documentation away from the forums (which was a great start), I've created a 'Manifesto' repository. I've put up an initial [README](https://github.com/elm-community/Manifesto) that tries to set out some guiding principles. Not that we need to be very bureaucratic, of course, but it can be helpful to say something :-)

So, take a look at that and see if it seems OK -- feel free to discuss here, or indeed make changes (you should all have write access to it).

I mentioned at the end of the README that I'm the 'owner' in Github terms. I've actually also made @laszlopandy an 'owner', for the sake of redundancy. But I didn't actually ask him if that's OK, so let me know if you'd prefer not to be!

**Comment by rgrempel** [comment]
I managed to get the [README](https://github.com/elm-community/Manifesto) link wrong at first -- I've corrected it now :-)

**Comment by mgold** [comment]
This all sounds good, but let's not get too caught up in "doing work about work". (I recognize that in large companies, "work about work" is very necessary, but for a few people in open source, let's cut to the chase.)

You can also have a look at [this thread](https://github.com/NoRedInk/elm-random-extra/pull/2#issuecomment-158845895) to see discussion of who should take ownership and maintenance vs. active development.

I'm hoping to write a guide about Randomness (after answering one too many SO questions). I also want to work on elm-package and smooth out the rough edges.
