### ISSUE TITLE
Fork circuithub/elm-json-extra?

### ISSUE THREAD

**Issue by lukewestby** [elm-community/Manifesto#10]
I've had a PR open there with no comment for 4 weeks, and the last activity was 2 months ago. There's a lot of really useful stuff in there, not the least of all `(|:)`, and I would imagine the community is interested in continuing to improve it. Thoughts?

**Comment by mgold** [comment]
Seems reasonable to me. I'd like to rename `apply` to `andMap`.

**Comment by lukewestby** [comment]
Good deal, forked!
