### ISSUE TITLE
Take over elm-dict-extra

### ISSUE THREAD

**Issue by robinheghan** [elm-community/Manifesto#12]
I'm the owner of the elm-dict-extra package. I would love for this package to be owned by the elm-community. What would I have to do for this to happen?

**Comment by eeue56** [comment]
Okay :+1: 

We're still discussing the best way of migrating things. The first that would need to happen is for @mgold or someone to add you to elm-community

**Comment by mgold** [comment]
@Skinney Transferring requires admin rights, which I'm about to give you. This is the obligatory "don't abuse it" speech.

**Comment by robinheghan** [comment]
Repository transferred

**Comment by eeue56** [comment]
Noting until the packages are published. No further input required from @Skinney at this time

**Comment by mgold** [comment]
Reopening until the repo is published.
