### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eeue56** [elm-community/Manifesto#14]
elm-community should have a logo!

**Comment by fredcy** [comment]
The Elm logo multiplied somehow, perhaps in 3D?

**Comment by mgold** [comment]
Or a tangram of a person?

**Comment by fredcy** [comment]
![screen shot 2016-03-23 at 4 42 50 pm](https://cloud.githubusercontent.com/assets/15950/14001924/956b766c-f116-11e5-90d5-1147625107e8.png)

**Comment by rgrempel** [comment]
I think that is fantastic!

**Comment by fredcy** [comment]
I took the liberty of adding that logo to the http://elm-community.github.io/ and http://elm-community.github.io/elm-faq/ pages.

I don't know what it takes to change the profile avatar of a github organization. I suspect that I don't have means to do that for elm-community.

**Comment by rgrempel** [comment]
It's in the settings for the organization -- I've switched it to the new logo -- thanks!

May I say again how much I like the logo? It's not just attractive -- it also really embodies the idea of the organization.
