### ISSUE TITLE
Shared CONTRIBUTING.md?

### ISSUE THREAD

**Issue by lukewestby** [elm-community/Manifesto#15]
It seems like contributions here are increasing as Elm continues to gain popularity which is awesome!

It could be helpful for people looking to contribute if there was a CONTRIBUTING.md on every project that just said stuff like "please include useful doc comments" and "make sure the `exposing` statements are up-to-date with added functionality" and "please be respectful in comments" and stuff like that.

Thoughts?

**Comment by eeue56** [comment]
Sounds good. Someone want to make a draft of this?

**Comment by prikhi** [comment]
I feel like it would make more sense to have a centralized contributing guide. It seems easier to just say, "see the contributing guide at elm-community/contrib or elm-community/Manifesto", instead of having to update contributing guides in every single elm-community repo after every change

**Comment by mgold** [comment]
I'll probably add a few things when I see the draft, but right off the bat I'd like to suggest: don't bump the version in `elm-package.json`.

**Comment by mgold** [comment]
Also how did nobody notice this for eight months?

**Comment by mgold** [comment]
Another suggestion: explain how elm-package enforces semvar, and then say not to make major/breaking changes if possible.

**Comment by prikhi** [comment]
If the repository has a changelog, add any user-facing changes to it.

**Comment by mgold** [comment]
> If the repository has a changelog, add any user-facing changes to it.

Under an "unreleased" header.
