### ISSUE TITLE
elm-webgl and elm-linear-algebra

### ISSUE THREAD

**Issue by rgrempel** [elm-community/Manifesto#2]
A couple of additional packages are possibly orphans as far as updating to Elm 0.16 goes:

https://github.com/elm-lang/package.elm-lang.org/issues/143

This is just a reminder to me to check in later to see what the status of this is.

**Comment by fredcy** [comment]
Let's do it. I submitted a [PR](https://github.com/johnpmayer/elm-linear-algebra/pull/14) 17 days ago to update elm-linear-algebra to 0.16 and there has been no response.

**Comment by rgrempel** [comment]
I've just sent @johnpmayer an email, asking how he wants to proceed. It really would be easier if we don't have to convince Evan to change the whitelist, so let's see if I get a reply to the email.

**Comment by rgrempel** [comment]
Well, I haven't got any response, so I guess we'd best go down this road.

So, I've cloned elm-webgl and elm-linearalgebra, and given @fredcy and @nphollon collaborator status on them -- that should give you the rights to commit changes, merge pull requests etc. If you could figure out between the two of you what needs to be done, that would be great.

I should say that it's not inevitable that Evan will want to change the native whitelist for this -- in one sense it is an exceptional situation, because people had been relying on these packages in Elm 0.15 -- so he might be willing (as with elm-history) to whitelist this. However, he might not, since there are a variety of considerations about native code and the package system which he is keeping in mind. In any event, it probably makes sense to do the work first, and then prepare a pull request explaining the situation for the whitelist.

Note that I'll be away for a week (without the Internet, on a sunny beach, I'm afraid). But I've arbitrarily created a few more "owners", so someone may be able to help if any owner-like actions are needed.

**Comment by fredcy** [comment]
I submitted https://github.com/elm-community/elm-linear-algebra/pull/1 to update elm-linear-algebra to run on elm 0.16.

@nphollon, per suggestion from @rgrempel I am not merging my own PR. Would you please look at it and either merge it or comment about what you would rather do.

P.S. We don't have issue tracking enabled for elm-linear-algebra. I think we should.

**Comment by fredcy** [comment]
Nevermind, @mgold is quick.

**Comment by mgold** [comment]
Yeah, no reason not to have our fork up to date, but it doesn't much matter until either the native whitelist gets updated or John merges his PR.

Alternatively, could we write a script to clone our repo and pretend it was John's?

**Comment by nphollon** [comment]
Agree with @fredcy about having issue tracking enabled for both repos.

@mgold I am not quite clear what kind of script you're thinking about, but I don't think it's possible to impersonate a different repo (for instance by changing elm-package.json). `elm package publish` checks for the correctly tagged version on github before publishing anything.

Thanks everybody for being on top of this... I've been busy lately with holiday travel.

**Comment by mgold** [comment]
My idea was to bypass `elm-package`, just a shell script to download the elm-community repo into `elm-stuff`. I don't think that any enforcement of who's allowed to use native modules is done once the packages are installed.

**Comment by nphollon** [comment]
Ah, that makes much more sense. Sounds like it might be worthwhile, considering all work on elm-webgl is blocked without a 0.17-compatible version of elm-linear-algebra.

Should we go ahead and open a native review for elm-community/elm-linear-algebra?

**Comment by jvoigtlaender** [comment]
Yes, I'd say: Open native review requests for elm-community/elm-linear-algebra and elm-community/elm-linear-algebra if/when they are updated to 0.16. There is reasonable hope that they might get fast-tracked for whitelisting, given Evan's recognition that they are kind of "urgently" needed, in [this comment of his](https://github.com/elm-lang/elm-lang.org/issues/462#issuecomment-166230270).

**Comment by nphollon** [comment]
One more concern... `elm package publish` will want us to restart at 1.0.0. In order to do this, we'll need to trash the existing version tags, which AFAIK is possible but frowned-upon. What's the least stupid way of doing this?

**Comment by mgold** [comment]
Having forked a repo before, just go ahead and trash the old tags. They're local to the fork so it's not catastrophic. Not pleasant, but it's what needs to happen.

**Comment by mgold** [comment]
You'll also need to reset the version in `elm-package.json` to 1.0.0. `elm package bump` will do this automatically now that the repo owner has been updated.

Also I enabled issues in the repo, so we can continue discussing over there if needed.

**Comment by nphollon** [comment]
@mgold Could you please enable issue tracking for elm-webgl as well? Thanks

**Comment by mietek** [comment]
Thanks for taking care of this.

**Comment by johnpmayer** [comment]
Happy Holidays!

Is there anything I can do to unblock this? At this point, I can't be the maintainer for a library with more than one user :smirk: 

Would updating the README on my repositories to point to the elm-community forks be best?

**Comment by nphollon** [comment]
If you could put a note in the READMEs, that would be really helpful. Thanks! Sorry you won't be able to keep maintaining 

Our big blocker right now is the native review...
https://github.com/elm-lang/package.elm-lang.org/issues/149

**Comment by mgold** [comment]
@johnpmayer Would it be okay if you added someone, probably @nphollon, as a collaborator on your native-approved repo? That way we could handle updates and README notices ourselves.

**Comment by nphollon** [comment]
They are released! 

http://package.elm-lang.org/packages/elm-community/elm-linear-algebra/latest/
http://package.elm-lang.org/packages/elm-community/elm-webgl/latest/

@rgrempel I think we can close this now?

**Comment by mgold** [comment]
Yay!
