### ISSUE TITLE
Future of elm-linear-algebra in Elm 0.17

### ISSUE THREAD

**Issue by fredcy** [elm-community/Manifesto#21]
The elm-linear-algebra package as it stands depends heavily on the Elm 0.16 "native" JS code scheme. What should we do about this package for Elm 0.17? I'm willing to take the lead in maintaining it but the only clear path open to me now is to re-code it in pure Elm.

**Comment by lukewestby** [comment]
Can the native parts not be rewritten using the 0.17 native format?

**Comment by eeue56** [comment]
Upgrading the native for this should be pretty simple

**Comment by fredcy** [comment]
Can you point me to a good example of native format in 0.17? I didn't realize that native was available anymore outside of the effect manager framework.

**Comment by eeue56** [comment]
A short but sweet example -> https://github.com/maxsnew/lazy/pull/11/files

**Comment by mgold** [comment]
Anyone want to step up to maintain the package and update the native format?

**Comment by fredcy** [comment]
I will give it a go. I'll close this issue and continue the conversation as necessary in the issues for that package.

**Comment by eeue56** [comment]
Feel free to ping me if you get stuck @fredcy
