### ISSUE TITLE
Migrate elm-random-extra from NRI

### ISSUE THREAD

**Issue by mgold** [elm-community/Manifesto#25]
@eeue56 It's a good library to have, and even though the new elm-test probably won't use it because it needs PCG's splittable seeds, I have [this PR](https://github.com/mgold/elm-random-sample/pull/2) indicating that folks want randomness helpers.

**Comment by eeue56** [comment]
👍

**Comment by mgold** [comment]
Thanks!

**Comment by egaga** [comment]
I am unable to find the package from http://package.elm-lang.org/
Can you point it out for me? Thank you! (I assume that closing this issue indicates it has been published there).

**Comment by mgold** [comment]
Nope, closing means it was moved over to the elm-community owner. It will be published in a few days.
