### ISSUE TITLE
Relationship with elm-guides

### ISSUE THREAD

**Issue by rgrempel** [elm-community/Manifesto#3]
@mgold (and others), I made @fredcy a member here for the sake of https://github.com/fredcy/elm-faq and given the discussion on the mailing list.

Is this the right place for that, compared with https://github.com/elm-guides? I had forked the repositories from elm-guides to here, based on the discussion of merging the two. But, I don't want to do anything high-handed, if you know what I mean :-)

**Comment by fredcy** [comment]
I am happy to put the elm-faq here (as opposed to elm-guides) if it's agreed that that's OK to do. I'll hold off until I see some confirmation (or timeout with no discussion).

**Comment by mgold** [comment]
Seems reasonable to me. You'd have to ask @jamischarles about how he feels shutting down elm-guides in favor of elm-community. But I personally would like to have a centralized third-party community, provided it doesn't become a cartel. That means giving out write access fairly liberally (perhaps to anyone who submits a good PR, and then asks), and admin access to... more than one person.

I think this gives us the best shot of having high-quality guides in a discoverable place. Reducing duplicated work is always good. And I'd like to see us host our own version of the official docs (see [this unmerged PR](https://github.com/elm-lang/elm-lang.org/pull/395)).

And no, I don't think the missions of third-party guides and maintaining important libraries conflict.

**Comment by fredcy** [comment]
OK, I pulled the trigger and forked my elm-faq repo into elm-community. I plan to maintain it here in its new home.

**Comment by rgrempel** [comment]
I just sent @jamischarles an invitation to be a member here -- not to pre-empt how he'd like to handle thing, but just to facilitate whatever he'd like to do.
