### ISSUE TITLE
Appropriate repo for a severalUpdates function?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/Manifesto#34]
There was this issue at `start-app`: https://github.com/evancz/start-app/issues/40

The function proposed there still makes sense. It would now have this signature:

``` elm
severalUpdates : (msg -> model -> (model, Cmd msg)) -> List msg -> model -> (model, Cmd msg)
```

A use case would be that in [this mailing list thread](https://groups.google.com/d/msg/elm-discuss/D08ddTkFILQ/l28O5ujRFwAJ) one solution would be to have:

``` elm
    IncrementBothCounters ->
        severalUpdates update [IncrementFirstCounter, IncrementSecondCounter] model
```

But where could such a function live? Does it fit with one of the existing `*-extra` repositories, or should there be a `cmd-extra`, `app-extra`, `program-extra`?

**Comment by mgold** [comment]
I think the best place for it among the existing -extra repo is basics-extra. It's not a perfect fit, but I prefer that to creating a library with one function.

**Comment by jvoigtlaender** [comment]
Actually found an appropriate home: https://github.com/ccapndave/elm-update-extra/issues/2

**Comment by mgold** [comment]
👏
