### ISSUE TITLE
Using elm-community.org

### ISSUE THREAD

**Issue by rgrempel** [elm-community/Manifesto#39]
I registered the domain `elm-community.org` in case it ever came in handy, and the `elm-webgl` repository is now using it for its `gh-pages` (e.g. http://webgl.elm-community.org/triangle.html).

I've also hooked things up so that you can see the organization pages for elm-community at either http://elm-community.github.io/ or http://elm-community.org/

If any of the other repos would like to use a subdomain of `elm-community.org`, just let me know -- I just have to set up a CNAME entry in the DNS record, which is no trouble at all.

**Comment by fredcy** [comment]
The elm-faq repo had been published at http://elm-community.github.io/elm-faq/. When I access that URL today it gets redirected to http://elm-community.org/elm-faq/

I'm OK with that change but I'm surprised that it happened.

**Comment by rgrempel** [comment]
Ah, I didn't realize that would happen -- I thought that it was opt-in on a per-repository basis. But, I guess when I did the CNAME in the `elm-community.github.io` repo, it must have had this side-effect for the other repos? I suppose that seems logical, now that I think about it a little more.

I can revert that if it's troublesome -- there wasn't any strong reason to do it -- just that since we were using `webgl.elm-community.org` now, it seemed to make sense to have `elm-community.org` itself point to something useful.

Alternatively, if you'd prefer something like `faq.elm-community.org` to `elm-community.org/elm-faq/`, I can arrange for that.

**Comment by fredcy** [comment]
Having `faq.elm-community.org` work sounds good, as long as the old URL (`elm-community.org/elm-faq/`) redirects there. How do we make that happen?

**Comment by rgrempel** [comment]
I've done the DNS entry required, so now it's just a matter of having a file called `CNAME` in the gh-pages branch, where the content of the file is `faq.elm-community.org`

I just tried that, and it worked (including the redirect), but it broke a ton of the internal links to CSS and the like, because they had been specified like `/elm-faq/...`, but now we're one level up, if you know what I mean. So, the links would need to be changed, perhaps to relative links?

In any event, I reverted the `CNAME` file for the moment.

**Comment by fredcy** [comment]
Relative links are not a good fit with how the Jekyll templates are currently set up.

I changed the `baseurl` in the config to be the default rather than "/elm-faq" and reinstated the CNAME file. With that in place it's working correctly for me. http://elm-community.github.io/elm-faq/ still redirects to http://faq.elm-community.org/ and the latter displays correctly.

Would someone else please verify that the FAQ pages are displaying correctly?

**Comment by jvoigtlaender** [comment]
Works for me.

**Comment by fredcy** [comment]
Thanks. So elm-faq is set.

Is there any other reason to keep this issue open?

**Comment by rgrempel** [comment]
Let's keep it open a few days in case any other repos have been using gh-pages.

**Comment by eeue56** [comment]
Closing due to no reply
