### ISSUE TITLE
Porting to 0.18

### ISSUE THREAD

**Issue by eeue56** [elm-community/Manifesto#42]
| Repo | Description | Maintainer github | Maintainer email | is ported |
|------|-------------|-------------------|------------------|-----------|
| [builtwithelm](http://github.com/elm-community/builtwithelm) | A list of projects and apps built with Elm. | lukewestby | opensource@lukewestby.com  | [ ] |
| [elm-webgl](http://github.com/elm-community/elm-webgl) | Functional 3D Rendering with WebGL in Elm | *Unmaintained* |  | [ x ] |
| [list-extra](http://github.com/elm-community/list-extra) | Convenience functions for working with List | abadi199 | abadi.kurniawan@gmail.com | [ x ] |
| [elm-compiler-docs](http://github.com/elm-community/elm-compiler-docs) | Repo where to write down documentation and guides for the elm-compiler | mgold | maxgoldstein1@gmail.com | [ ] |
| [json-extra](http://github.com/elm-community/json-extra) | Convenience functions for working with Json | lukewestby | opensource@lukewestby.com | [x] |
| [Manifesto](http://github.com/elm-community/Manifesto) | Meta-repository for organizational stuff | *Unmaintained* |  | [ ] |
| [array-extra](http://github.com/elm-community/array-extra) | Convenience functions for working with Array | jonboiser | jonboiser@outlook.com | [ ] |
| [maybe-extra](http://github.com/elm-community/maybe-extra) | Convenience functions for working with Maybe | abadi199 | abadi.kurniawan@gmail.com | [ x ] |
| [result-extra](http://github.com/elm-community/result-extra) | Convenience functions for working with Result | abadi199 | abadi.kurniawan@gmail.com | [ x ] |
| [elm-material-icons](http://github.com/elm-community/elm-material-icons) | Material Icons in Elm | mgold | maxgoldstein1@gmail.com | [ ] |
| [elm-faq](http://github.com/elm-community/elm-faq) | FAQ about the Elm language | fredcy | fredcy@gmail.com  | [ na?] |
| [html-extra](http://github.com/elm-community/html-extra) | Additional functions for working with Html | *Unmaintained* |  | [x] |
| [elm-for-js](http://github.com/elm-community/elm-for-js) | Community driven Elm guide for JS people | *Unmaintained* |  | [ ] |
| [elm-linear-algebra](http://github.com/elm-community/elm-linear-algebra) | Enough linear algebra to support elm-webgl | fredcy | fredcy@gmail.com | [ XX ] |
| [undo-redo](http://github.com/elm-community/undo-redo) | Easy undo in Elm | rohanorton | rohan.orton@gmail.com | [ ] |
| [list-split](http://github.com/elm-community/list-split) | Split lists into chunks | jonboiser | jonboiser@outlook.com  | [ ] |
| [elm-lang.org](http://github.com/elm-community/elm-lang.org) | The full source for http://elm-lang.org/, the home-page of the Elm programming language. Open sourced as a way to teach people how to write and serve Elm code. Follow the instructions in README.md to get the site setup on your own machine. | *Unmaintained* |  | [ ] |
| [elm-community.github.io](http://github.com/elm-community/elm-community.github.io) | Elm Community organization pages | *Unmaintained* |  | [ ] |
| [dict-extra](http://github.com/elm-community/dict-extra) | A library with extra functions for the dictionary type in elm core | Skinney | robin.heggelund@icloud.com | [ x ] |
| [lazy-list](http://github.com/elm-community/lazy-list) | Lazy list implementation in Elm | mgold |  maxgoldstein1@gmail.com | [ x ] |
| [random-extra](http://github.com/elm-community/random-extra) | Extra functions for Random | mgold |  maxgoldstein1@gmail.com | [ x ] |
| [shrink](http://github.com/elm-community/shrink) | Shrink a value to a simpler one | mgold |  maxgoldstein1@gmail.com | [ x ] |
| [elm-test](http://github.com/elm-community/elm-test) | A unit testing framework for Elm | rtfeldman | richard.t.feldman@gmail.com | [ x ] |
| [elm-check](http://github.com/elm-community/elm-check) | Property-based testing | mgold |  maxgoldstein1@gmail.com | [ x ] |
| [basics-extra](http://github.com/elm-community/basics-extra) | Additional basic functions | jvoigtlaender |  janis.voigtlaender@gmail.com | [ x ] |
| [easing-functions](https://github.com/elm-community/easing-functions) |  Easing (animation and timing) library for Elm | Dandandan | danielheres@gmail.com | [ ] |
| [svg-extra](http://github.com/elm-community/svg-extra) | Additional functions for working with Svg | jvoigtlaender | janis.voigtlaender@gmail.com | [x] |
| [intdict](http://github.com/elm-community/intdict) | Optimized dictionary specialization for Integers. Mirrors the dictionary API. | sgraf812 | sgraf1337@gmail.com | [ x ] |
| [graph](http://github.com/elm-community/graph) | Functional Graph Library in Elm | sgraf812 | sgraf1337@gmail.com | [ ] |
| [string-extra](http://github.com/elm-community/string-extra) | String helper functions for Elm | lorenzo & jaapz | jose.zap@gmail.com & jaapz.b@gmail.com | [ x ] |

**Comment by eeue56** [comment]
cc @elm-community/maintainers please update your packages to 0.18 and publish them against the beta site. For now, we can consider our repos frozen until 0.18 is released.

**Comment by sgraf812** [comment]
Is there a list of breaking changes somewhere? Is there a `HEAD` version of the compiler or do I have to compile it myself?

**Comment by eeue56** [comment]
https://groups.google.com/forum/#!topic/elm-dev/ddNPpn9aE6s

and

https://gist.github.com/evancz/8032a3ac6eb7a4ac8e0956ed6d386798

**Comment by jvoigtlaender** [comment]
Do we have a plan for how to go about the two packages currently marked "Unmaintained"?
- https://github.com/elm-community/elm-webgl
- https://github.com/elm-community/html-extra

I may try to have a go at updating `html-extra`, but we shouldn't duplicate work.

**Comment by jvoigtlaender** [comment]
Have updated https://github.com/elm-community/html-extra to 0.18, and also taken the opportunity to add [`Html.Attributes.Extra.static`](http://package.elm-lang.org:8018/packages/elm-community/html-extra/2.1.0/Html-Attributes-Extra#static).

**Comment by eeue56** [comment]
not sure about elm-webgl. It's not a thing used in production so I don't consider it top priority. Maybe wait til someone requests it?

@elm-community/maintainers please comment when you have updated packages so i can tick them off :+1: thanks in advance!

**Comment by robinheghan** [comment]
I'm waiting for elm-test to be available. Not updating until I can get working unit tests.

**Comment by rtfeldman** [comment]
@mgold is looking into a regression on `Random.Pcg`, and the elm-test upgrade is blocked on that. Stay tuned!

**Comment by lukewestby** [comment]
json-extra is good

**Comment by jvoigtlaender** [comment]
The following are updated from my side:
- https://github.com/elm-community/basics-extra
- https://github.com/elm-community/html-extra
- https://github.com/elm-community/svg-extra

**Comment by fredcy** [comment]
I have updated the elm-linear-algebra package and published it to the beta server. No code changes were required, only elm-package.json changes.

Its tests do not build yet. I'll update those when elm-test is available.

Edit: The tests are now running again. I just published patch version 2.0.5. This package is all ready for 0.18.

**Comment by mgold** [comment]
I have fixed the randomness issue that blocked elm-test, so that should be up soon.

**Comment by jaapz** [comment]
Whenever elm-test is working on 0.18 we can make sure string-extras is too

**Comment by rtfeldman** [comment]
`elm-test` is now  👍

**Comment by sgraf812** [comment]
I was a little eager on `elm package publish`. Is there a way to undo that? Otherwise I can just wait until 0.18 is released...

**Comment by eeue56** [comment]
@sgraf812 what do you mean by that?

**Comment by sgraf812** [comment]
I published v2.0.0 on the temporary package registry without really having run/compiled the tests (yeah, I know...), so I just fixed up the test suite. I force pushed the v2.0.0 tag to the new commit and would like to have a way to update the registry now.

No problem if that's not possible, the actual library code didn't change anyway. Also I think that since the GitHub repo points to the right commit, it will actually download the right thing.

**Comment by eeue56** [comment]
That's okay, we'll need to re-publish on the live server anyway (so you can just force-push the tags for now)

**Comment by abadi199** [comment]
https://github.com/elm-community/list-extra is updated.

**Comment by robinheghan** [comment]
elm-community/dict-extra is updated.

**Comment by lorenzo** [comment]
https://github.com/elm-community/string-extra is updated but I'm getting an error when trying to publish to the beta site. 

```
Verifying elm-community/string-extra 2.0.0 ...
Error: The following HTTP request failed.
<http://package.elm-lang.org:8018/documentation?elm-package-version=0.18&name=elm-community%2Fstring-extra&version=1.1.0>

That library and version is not registered.
```

**Comment by sgraf812** [comment]
elm-community/intdict is updated.

**Comment by abadi199** [comment]
https://github.com/elm-community/maybe-extra is updated

**Comment by abadi199** [comment]
https://github.com/elm-community/result-extra is updated

**Comment by mgold** [comment]
https://github.com/elm-community/shrink is done
https://github.com/elm-community/lazy-list is done
https://github.com/elm-community/elm-check is deprecated in favor of elm-test
https://github.com/elm-community/elm-compiler-docs contains no code
https://github.com/elm-community/random-extra is TODO
https://github.com/elm-community/elm-material-icons is TODO

**Comment by rtfeldman** [comment]
@mgold https://github.com/rtfeldman/legacy-elm-test still uses `elm-community/elm-check`, and I'd like to release an 0.18 update for that.

I think it'd be reasonable to deprecate it for 0.19 and say "the time has come to migrate" but I think now would be too soon.

**Comment by mgold** [comment]
@rtfeldman, I had a busy weekend, but I've just updated `random-extra` and `elm-check`.

I should probably stop maintaining `elm-material-icons`.

**Comment by rtfeldman** [comment]
Thanks @mgold! `rtfeldman/legacy-elm-test` is now published for 0.18.

**Comment by rohanorton** [comment]
https://github.com/elm-community/undo-redo updated

**Comment by jonboiser** [comment]
`list-split` and `array-extra` have been updated

**Comment by eeue56** [comment]
@elm-community/maintainers  Thanks to everyone who updated! Now it's time to re-publish against the actual package site. Let me know of any problems ASAP and I can loop evan in

**Comment by lukewestby** [comment]
Looks like json-extra is already republished. Thanks to whoever pushed it up!

**Comment by mgold** [comment]
I've republished `elm-check` to that @rtfeldman can republish the legacy elm-check package. I think everything else I maintain has already been taken care of?

**Comment by rtfeldman** [comment]
Upgraded - thanks @mgold!

**Comment by w0rm** [comment]
@eeue56 please mark webgl as ported!
