### ISSUE TITLE
Additional owners

### ISSUE THREAD

**Issue by rgrempel** [elm-community/Manifesto#6]
I'm going to be away for the next week, without Internet access. (We're going somewhere very sunny for Christmas this year). So, in the interest of avoiding anything blocking needlessly, I've arbitrarily appointed @mgold and @Apanatshka to be "owners" of @elm-community (in Github terms).

**Comment by mgold** [comment]
Sweet, thanks!

**Comment by Apanatshka** [comment]
Thanks. Just a warning though: I'm extremely busy and have turned off GitHub's notifications, so I will be very slow to help out at the moment. Now that I know, I'll try to check my GitHub notifications at least once a week.

**Comment by rgrempel** [comment]
I've now also added @jvoigtlaender as an owner, and created an @elm-community/owners team, so you can ping all the owners at once if you like.
