### ISSUE TITLE
Move NoRedInk/elm-task-extra to elm-community/task-extra

### ISSUE THREAD

**Issue by avh4** [elm-community/Manifesto#62]
Hello, we'd like to see if elm-community is interested in taking over https://github.com/NoRedInk/elm-task-extra

This is an extras package for working with Tasks, and seems like a good fit for living in elm-community.

I could be the interim maintainer until a new maintainer is found.

**Comment by eeue56** [comment]
Is this package actually in use?

**Comment by avh4** [comment]
Yes, we had a PR from someone who wants it updated to Elm 0.18:  https://github.com/NoRedInk/elm-task-extra/pull/3

**Comment by avh4** [comment]
Hmm... looking at it, `never` and `performFailproof` are now in core... maybe there's nothing worth keeping.   I'll check with the original requester.

**Comment by avh4** [comment]
We've decided to deprecate the package instead of moving it to elm-community.
