### ISSUE TITLE
CONTRIBUTING.md or PR template

### ISSUE THREAD

**Issue by mgold** [elm-community/Manifesto#64]
I made a [reddit post](https://www.reddit.com/r/elm/comments/5sbjcb/psa_dont_bump_package_version_with_prs/) that asks contributors to not bump the package version with PRs. It also mentioned running the compiler and tests before submitting. I put up the post without intending further action, but commenters mentioned that writing up either a `CONTRIBUTING.md` or PR/issue template would be useful.

I'm skeptical how many people read these things (hence Evan's insistence on ProcessBot) and it's not plausible to add them to every Elm project. But one commenter wrote,

> However, this needs to be enforced and it needs to be modeled by the community. `elm-community` could be a place where all these things could be modeled for others to see and follow.

So, maybe we should look into a standard set of contributing documents. Once we get them ironed out, we can add them to all our repos. Hopefully enough people will see them, and non-community library maintainers will copy them, to improve the quality of contributions.

**Comment by prikhi** [comment]
Dupe of #15? Or just related?

**Comment by mgold** [comment]
Probably a dupe, but with a new justification.
