### ISSUE TITLE
Adopt canadaduane/typed-svg?

### ISSUE THREAD

**Issue by canadaduane** [elm-community/Manifesto#69]
Leaving this here as a discussion point per Noah's request, so I can point interested parties here.

`TypedSvg` is an attempt to replace the `elm-lang/svg` package with a fully typed (and documented) equivalent. Some reasonable module separation has been included (for instance, to keep filters in their own modules, and my intent was to move animations to their own module as well). In addition, there are some convenience modules that help with common things like unit lengths (InPx, InEm) so that specifying the unit on every call is unnecessary.

I'd be happy if elm-community decided to adopt this, as I will be moving on from Elm.

https://github.com/canadaduane/typed-svg

**Comment by eeue56** [comment]
Needs someone to step forward as maintainer

**Comment by rupertlssmith** [comment]
Happy to be the maintainer. I'll be using this library a lot in the coming months so I have an interest in looking after it. Also, many thanks to Duane for getting it this far.

**Comment by eeue56** [comment]
Are you familiar with how to publish a package?

**Comment by mgold** [comment]
[In case you're not.](https://medium.com/@Max_Goldstein/how-to-publish-an-elm-package-3053b771e545)

**Comment by rupertlssmith** [comment]
Yes.

**Comment by avh4** [comment]
FYI, I'd be happy to help review PRs for typed-svg (though wouldn't have time for active development).

@rupertlssmith, since you're stepping up, feel free to ping me if you ever need an extra hand.

**Comment by eeue56** [comment]
@rupertlssmith Please open a like [this](https://github.com/elm-community/Manifesto/pull/65)

@canadaduane Please transfer typed-svg to me. Thanks for your work on it, it's in good hands!

**Comment by canadaduane** [comment]
Transferred. Thanks all!

**Comment by rupertlssmith** [comment]
Hopefully, this is what you meant:

https://github.com/elm-community/Manifesto/issues/70

**Comment by eeue56** [comment]
@canadaduane Please fork it back to your account -- right now, nobody can install typed-svg from you. That's my bad, I should've said. I'll make a checklist to make this easier in future.

**Comment by gampleman** [comment]
> FYI, I'd be happy to help review PRs for typed-svg (though wouldn't have time for active development).

Same here.

**Comment by canadaduane** [comment]
Forked.
