### ISSUE TITLE
Relationship with elm-hub

### ISSUE THREAD

**Issue by fredcy** [elm-community/Manifesto#8]
There is now https://github.com/elm-hub that seems to have a mission overlapping that of elm-community. Perhaps we could reach out to see if we can join forces.

**Comment by mgold** [comment]
Seems to be just one guy. Someone want to take the lead?

**Comment by fredcy** [comment]
I chatted with him on the Slack channel. He said that he contacted someone here at elm-community a while back but got little response.

**Comment by fredcy** [comment]
This seems to be going nowhere. I'm abandoning my request.
