### ISSUE TITLE
Result-Extra maintainer MIA?

### ISSUE THREAD

**Issue by cynic** [elm-community/Manifesto#94]
I've just put in a PR for Result-Extra and have noticed 4 other PRs open since around May 2017 with no comment or resolution.  Does anyone know where @abadi199 is?

**Comment by prikhi** [comment]
I'd be down to take over or co-maintain the package.

**Comment by cynic** [comment]
I'd be down to take over or co-maintain it, too, if it comes to that!  The 7 days mentioned in the Manifesto have passed... so, does anyone know what the next step on the path to getting Result-Extra maintained is?

**Comment by abadi199** [comment]
Hi everyone, sorry about this. I really don't have time be the maintainer of this package anymore, so I'll step down. @prikhi and @cynic, just open a PR, remove me, and add yourself on https://github.com/elm-community/Manifesto/blob/master/maintainers.md, and I'll approve it.

**Comment by cynic** [comment]
Great, thanks @abadi199 !  @prikhi , I'll drop my name in on Monday if you haven't submitted a PR by then 😄 .
